### ISSUE TITLE
Missing projperty sonar.projectKey

### ISSUE THREAD

**Issue by oko-x** [ciricihq/gitlab-sonar-scanner#21]
After yesterday's remove of unnecessary assignment `SONAR_PROJECT_KEY=$CI_PROJECT_NAME,` I get 

> You must define the following mandatory properties for 'Unknown': sonar.projectKey

my yml config looks like this:
```
sonarqube:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: "https://sonarurl.sonar"
    SONAR_ANALYSIS_MODE: "issues"
    SONAR_TOKEN: "token"
    SONAR_PROJECT_KEY: "$CI_PROJECT_NAME"
    SONAR_PROJECT_NAME: "$CI_PROJECT_NAME"
    SONAR_PROJECT_VERSION: "$CI_JOB_ID"
    SONAR_GITLAB_PROJECT_ID: "$CI_PROJECT_ID"
  script:
    - /usr/bin/sonar-scanner-run.sh
  tags:
    - runner
```

Should I add it to the script execution like `/usr/bin/sonar-scanner-run.sh -Dsonar.projectKey=$CI_PROJECT_NAME` ?
