### ISSUE TITLE
ISSUES mode is somehow buggy, despite the fact it works most of the times

### ISSUE THREAD

**Issue by MuyBien** [ciricihq/gitlab-sonar-scanner#23]
Hi!
Thanks for this image that save me a lot of time and effort!

But if I manage to connect the docker and the sonar server, it seems that it's analysing all the source files (10min) even in ISSUE mode.

Here is my gitlab-ci job 
```
SonarQube:
  stage: quality
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://sonar.***.***
    SONAR_ANALYSIS_MODE: issues
  script:
  - gitlab-sonar-scanner
  allow_failure: true
```

and my sonar-project.properties
```
sonar.sources=.
sonar.java.binaries=*/build
sonar.sourceEncoding=ISO-8859-1

sonar.gitlab.project_id=git@gitlab.***.***:2003/*******/***.git
```

In the job log it says:
`INFO: 18831/18831 source files have been analyzed`
